sudo: required
language: cpp
dist: xenial
branches:
    only:
        - master
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:texus/tgui-0.8'
        update: true
        packages:
            - g++-7
            - libsfml-dev
            - libtgui-dev
jobs:
    include:
        - stage: build
          name: build
          script: make CXX=g++-7
stages:
    - dependencies
    - build
