sudo: required
language: cpp
branches:
    only:
        - master
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        update: true
        packages:
            - g++-7
            - libsfml-dev
jobs:
    include:
        - stage: build
          name: build
          script: make CXX=g++-7
stages:
    - build
